categories:
- Data Managers
- Epigenetics
description: Contains a data manager that defines and populates the TCGA Expression, Methylation and Clinical data for ELMER.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: |
    Download the TCGA data for ELMER in RData format and add to data table
name: data_manager_elmer_tcga
owner: iuc
remote_repository_url: https://github.com/nitesh1989/tools-iuc/tree/methylation/data_managers/data_manager_elmer_tcga
type: unrestricted
